#!/usr/bin/env python3
"""Trace the HOBBYTAN AI logo rasters into vector SVGs.

    python3 scripts/brand/trace_logo.py

Reads  public/assets/brand/source/hobbytan-logo-{black,white}.webp  (RGBA)
Writes public/assets/brand/hobbytan-logo-{black,white}.svg          (standalone)
       src/logo.js  (per-letter inline SVG for animation, colours via CSS)

Each version is traced from its own source (they differ slightly in weight).
Requires: pip install numpy pillow scipy scikit-image
"""
import json
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage
from skimage import measure

ROOT = Path(__file__).resolve().parents[2]
BRAND = ROOT / 'public/assets/brand'
NAMES = ['H', 'O', 'B', 'B', 'Y', 'T', 'A', 'N']


def trace(src, ink_is_light):
    a = np.array(Image.open(src)).astype(float) / 255.0
    alpha, lum = a[..., 3], a[..., :3].mean(-1)
    ink, knock = alpha * (1 - lum), alpha * lum  # letters + badge box / the "AI" inside it
    if ink_is_light:
        ink, knock = knock, ink

    def shapes(field, min_area=200):
        lab, n = ndimage.label(field > 0.5)
        res = []
        for i in range(1, n + 1):
            ys, xs = np.where(lab == i)
            if len(xs) < min_area:
                continue
            x0, y0 = max(xs.min() - 2, 0), max(ys.min() - 2, 0)
            x1, y1 = xs.max() + 3, ys.max() + 3
            mask = ndimage.binary_dilation(lab[y0:y1, x0:x1] == i, iterations=2)
            crop = np.pad(np.where(mask, field[y0:y1, x0:x1], 0.0), 1)
            d = ''
            for c in measure.find_contours(crop, 0.5):
                c = measure.approximate_polygon(c, tolerance=0.3)
                if len(c) < 3:
                    continue
                # contour coords are pixel centres; SVG pixels span [i, i+1]
                d += 'M' + 'L'.join(f'{p[1] - 0.5 + x0:.1f} {p[0] - 0.5 + y0:.1f}' for p in c) + 'Z'
            res.append({'x': xs.min(), 'box': (xs.min(), ys.min(), xs.max(), ys.max()), 'd': d})
        return sorted(res, key=lambda s: s['x'])

    body, ai = shapes(ink), shapes(knock)
    bx = [s['box'] for s in body]
    x0, y0 = min(b[0] for b in bx) - 2, min(b[1] for b in bx) - 2
    w, h = max(b[2] for b in bx) - x0 + 3, max(b[3] for b in bx) - y0 + 3
    # body = 8 letters, the badge box, then any box-coloured pieces inside the "AI" (the A's counter)
    return f'{x0:.1f} {y0:.1f} {w:.1f} {h:.1f}', body[:8], body[8], body[9:], [s['d'] for s in ai]


def standalone(parts, fg, ai_fill):
    vb, word, box, inner, ai = parts
    p = [f'<path fill-rule="evenodd" fill="{fg}" d="{s["d"]}"/>' for s in [*word, box]]
    p += [f'<path fill-rule="evenodd" fill="{ai_fill}" d="{d}"/>' for d in ai]
    p += [f'<path fill-rule="evenodd" fill="{fg}" d="{s["d"]}"/>' for s in inner]
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" role="img" aria-label="HOBBYTAN AI">'
            f'<title>HOBBYTAN AI</title>{"".join(p)}</svg>\n')


def inline(parts):
    vb, word, box, inner, ai = parts
    g = [f'<path class="logo__l" data-l="{NAMES[i]}" fill-rule="evenodd" d="{s["d"]}"/>' for i, s in enumerate(word)]
    badge = f'<path class="logo__box" fill-rule="evenodd" d="{box["d"]}"/>'
    badge += ''.join(f'<path class="logo__ai" fill-rule="evenodd" d="{d}"/>' for d in ai)
    badge += ''.join(f'<path class="logo__box" fill-rule="evenodd" d="{s["d"]}"/>' for s in inner)
    g.append(f'<g class="logo__l logo__badge" data-l="AI">{badge}</g>')
    return f'<svg class="logo" viewBox="{vb}" aria-hidden="true" focusable="false">{"".join(g)}</svg>'


black = trace(BRAND / 'source/hobbytan-logo-black.webp', ink_is_light=False)
white = trace(BRAND / 'source/hobbytan-logo-white.webp', ink_is_light=True)
(BRAND / 'hobbytan-logo-black.svg').write_text(standalone(black, '#000', '#fff'))
(BRAND / 'hobbytan-logo-white.svg').write_text(standalone(white, '#fff', '#000'))
(ROOT / 'src/logo.js').write_text(
    '// Generated by scripts/brand/trace_logo.py from the white logo. Do not edit by hand.\n'
    '// Letters and badge use fill: var(--logo-fg); the "AI" uses fill: var(--logo-ai).\n'
    f'export const LOGO_SVG = {json.dumps(inline(white))};\n')
print('wrote', BRAND / 'hobbytan-logo-black.svg', BRAND / 'hobbytan-logo-white.svg', ROOT / 'src/logo.js')
